services:
  quant-ux-frontend:
    image: quant-ux-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        QUX_HTTP_PORT: ${QUX_HTTP_PORT:-9000}
    container_name: quant-ux-frontend
    environment:
      QUX_HTTP_PORT: ${QUX_HTTP_PORT:-9000}
      QUX_PROXY_URL: ${QUX_PROXY_URL:-}
      QUX_MC_CLASSROOM_URL: ${QUX_MC_CLASSROOM_URL:-}
      QUX_SHARED_LIBS: ${QUX_SHARED_LIBS:-}
      QUX_USER_ALLOWED_DOMAINS: ${QUX_USER_ALLOWED_DOMAINS:-*}
      QUX_DEV_HOSTNAME: ${QUX_DEV_HOSTNAME:-localhost}
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "${QUX_HTTP_PORT:-9000}:${QUX_HTTP_PORT:-9000}"
    restart: unless-stopped
    volumes:
      - .:/usr/src/quant-ux-frontend
      - /usr/src/quant-ux-frontend/node_modules
