ARG NODE_VERSION=16
ARG ALPINE_VERSION=
FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS dependencies

WORKDIR /usr/src/quant-ux-frontend

ENTRYPOINT [ "./entrypoint.local.sh" ]

CMD [ "npm", "run", "serve"]