services:
  quant-ux-frontend:
    image: quant-ux-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: quant-ux-frontend
    env_file:
      - .env
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./
          target: /home/node
          ignore:
            - node_modules/
            - dist/
            - .env
            - .env.local
            - .env.development.local
            - .env.test.local
            - .git/
        - action: restart
          path: vue.config.js
        - action: rebuild
          path: package.json
        - action: rebuild
          path: package-lock.json
        - action: rebuild
          path: yarn.lock
        - action: rebuild
          path: Dockerfile.local
        - action: rebuild
          path: docker-compose.yaml
